<?php

echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
echo "OKOKOKOOKOKOKOOKOOKOKOOKOOKOKOKO";
